### PR TITLE
Added iheatmapr graph for RNAseq (iheatmapr.custom)

### PR DESCRIPTION
**Pull request by curadomr**
- iheatmapr package generates plot with its own class, which is **not** plotly
- is has, though, functions to_plotly_json and to_plotly_list to facilitate conversion to plotly
- still, there is a need to discuss how to handle processing this graph in ON. This is because ON already runs plotly_json(). 
As of now, iheatmapr cannot be displayed in ON FE.

### CODE REVIEW

**Comment by curadomr** [comment]
iheatmapr can be used in a custom plotting function, but user needs to make few conversions like plotly::plotly_build(iheatmapr::to_plotly_list(p)) to make the iheatmapr object in plotly format, which is then read by ON.

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
@curadomr Thanks for the PR! And great job figuring out how to combine `plotly::plotly_build()` and `iheatmapr::to_plotly_list()`.

I confirmed:

1. That I could run `build.R` runs on my local machine
2. I can see the iheatmapr custom plot when running the single user server
3. That iheatmapr re-exports the magrittr pip `%>%` ([NAMESPACE](https://cran.r-project.org/web/packages/iheatmapr/NAMESPACE))


Before merging, let's wait for 1) Brett's review, and 2) for me to update the internal CD pipeline (currently it doesn't automatically install new packages, so it's going to fail when it tries to load iheatmapr)

**Comment by jdblischak** [comment]
The internal CD pipeline is ready for this PR to be merged

**Comment by jdblischak** [comment]
Shoot. I always forget this. We need to remember to bump the version number of the package when we add new features. It's not required, but this makes it easier to confirm that the new version is installed on our internal servers.

https://github.com/abbvie-external/OmicNavigatorExample/blob/4e22455d5875b94aaba6149840213ab992dd7bdf/build.R#L13-L15

**Pull request merged**
